import React, { Component } from 'react';

import Order from '../../components/Order/Order';
import axios from '../../axios-orders';
import withErrorHandler from '../../hoc/withErrorHandler/withErrorHandler';

class Orders extends Component {
    state = {
        orders: [], 
        loading: true
    }

    componentDidMount() {
        axios.get('/orders.json')
            .then(res => {
                console.log(res.data);

                // We get back an object
                // Turn that into an array
                const fetchedOrders = [];

                for(let key in res.data) {
                    // We create a new object and add an id key
                    // using the id generated by firebase
                    fetchedOrders.push({
                        ...res.data[key], 
                        id: key
                    });
                }
                this.setState({
                    loading: false, 
                    orders: fetchedOrders
                });
            })
            .catch(err => {
                this.setState({ loading: false });
            })
    }
    
    render() {
        return (
            <div>
                {this.state.orders.map(order => (
                    <Order 
                        key={order.id} 
                        ingredients={order.ingedients} 
                        price={order.price} />
                ))}
            </div>
        );
    }
}

export default withErrorHandler(Orders, axios);